"""Sub-task 6 - Text Generation: draft the message sent back to the patient.

Category: Natural Language Processing
Model:    Qwen/Qwen2.5-1.5B-Instruct

The generated text is advisory only. A safety layer prepends an emergency
instruction when the triage stage raised an emergency flag, and a fixed
disclaimer is always appended, so the model is never the last word on care.
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.append(str(Path(__file__).resolve().parent.parent))

import config
from llmops.metrics import tracked
from tasks import model_hub

DISCLAIMER = (
    "This message is generated by an automated triage assistant and is not a "
    "diagnosis. A qualified clinician will review your case."
)

EMERGENCY_BANNER = (
    "URGENT: your description contains an emergency warning sign. "
    "Call the ambulance service on 108 or go to the nearest emergency "
    "department immediately. Do not wait for a callback."
)

SYSTEM = (
    "You are a hospital triage assistant. You write short, calm, plain-language "
    "messages to patients. You never name a specific medicine, never state or "
    "suggest a diagnosis or condition name, and never use placeholders such as "
    "square brackets. Address the patient directly as 'you'."
)

# The classifier's provisional condition is deliberately NOT given to the
# generator. It only exists to drive the urgency band, and when the rule layer
# has escalated, it is known to be unreliable; an early version passed it in
# and the model told an emergency chest-pain patient they might have dengue.
PROMPT = """Patient complaint: {transcript}
Urgency: {urgency}
Next step decided by the triage desk: {routing}
Relevant hospital policy: {policy}

Write three or four sentences to the patient. Acknowledge the symptoms they
described, state the next step that has been arranged, and give one practical
thing they can do meanwhile. Do not name any illness or condition. Do not add
a greeting line or a signature."""


@tracked("6_patient_guidance", config.GENERATOR_MODEL)
def draft_reply(
    transcript: str,
    condition: str,
    urgency: str,
    routing: str,
    policy: str = "",
) -> dict:
    """Generate the patient-facing response with the safety layer applied."""
    gen = model_hub.generator()
    if gen is None:
        # Lite deployment: no generative model fits in the memory budget, so
        # the reply is composed deterministically. Structurally it makes the
        # same promises as the generated one - acknowledge, state the next
        # step, one practical instruction - and by construction it can never
        # name a condition or a medication.
        step = {
            "EMERGENCY": "Emergency care has been arranged for you right now.",
            "HIGH": "A same-day consultation with a specialist has been "
                    "booked for you.",
            "ROUTINE": "A standard out-patient appointment will be scheduled "
                       "for you within the next few days.",
        }.get(urgency, routing)
        out = (
            "Thank you for describing your symptoms; the triage team has "
            f"reviewed them. {step} In the meantime, please rest, stay "
            "hydrated, and avoid strenuous activity. If your symptoms "
            "worsen, seek emergency care immediately."
        )
    else:
        prompt = PROMPT.format(
            transcript=transcript[:900],
            urgency=urgency,
            routing=routing,
            policy=(policy or "No specific policy retrieved.")[:600],
        )
        out = gen(SYSTEM, prompt, max_new_tokens=200)

    # Strip any greeting or signature the model adds despite the instruction.
    lines = [ln.strip() for ln in out.splitlines() if ln.strip()]
    drop = ("dear ", "hi ", "hello", "sincerely", "regards", "best wishes", "warm ")
    lines = [ln for ln in lines if not ln.lower().startswith(drop)]
    out = " ".join(lines).strip()

    # Deterministic backstop: the model must not tell the patient the
    # provisional condition, even though it no longer sees it in the prompt.
    # Any sentence that names it (e.g. the policy passage mentioned it) is
    # dropped whole rather than edited, so the remaining text stays coherent.
    if condition:
        needle = condition.lower()
        sentences = [s.strip() for s in out.split(". ") if s.strip()]
        kept = [s for s in sentences if needle not in s.lower()]
        if kept and len(kept) < len(sentences):
            out = ". ".join(kept)
            if not out.endswith("."):
                out += "."

    body = out
    if urgency == "EMERGENCY":
        body = f"{EMERGENCY_BANNER}\n\n{body}"

    message = f"{body}\n\n{DISCLAIMER}"

    # Guard against the model degenerating into a very short or empty reply.
    generated_words = len(out.split())
    quality = min(1.0, generated_words / 40.0)

    return {
        "message": message,
        "generated_body": out,
        "generated_words": generated_words,
        "safety_banner_applied": urgency == "EMERGENCY",
        "confidence": round(quality, 4),
    }
